# Generated by Django 4.2.4 on 2023-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.CharField(max_length=15)),
                ("destination_ip", models.CharField(max_length=15)),
                ("source_port", models.PositiveIntegerField()),
                ("destination_port", models.PositiveIntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("packet_length", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("flag_packet", models.CharField(max_length=10)),
                ("data_payload", models.TextField()),
                ("label", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "tbldata",
            },
        ),
    ]
